name: M3U Rewrite

on:
  push:
    paths:
      - "1UmitTV.m3u"
      - "umitrew.py"
  workflow_dispatch:

jobs:
  rewrite:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Push izni ver

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python 3 kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Scripti çalıştır
        run: python umitrew.py

      - name: playlist.m3u var mı?
        run: |
          ls -l playlist.m3u || echo "playlist.m3u oluşturulamadı"

      - name: Dosyayı commitle ve gönder
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Otomatik: playlist.m3u güncellendi" || echo "Commit yok"
          git push origin main
